language: generic
services: docker

script:
  - >
    docker run -v=$(pwd):/app --workdir=/app
    coala/base coala --ci
  - docker build -t rultor-python -f Dockerfile .
  - docker images
  # Test building and installing coala
  - >
    docker run --rm rultor-python sh -c
    "git clone https://github.com/coala/coala &&
     cd coala &&
     pip3 install -r requirements.txt &&
     python3 setup.py bdist_wheel &&
     pip3 install ./dist/coala-*.whl &&
     cd .. &&
     git clone https://github.com/coala/coala-bears &&
     cd coala-bears &&
     pip3 install -r requirements.txt &&
     python3 -m nltk.downloader punkt \
                                averaged_perceptron_tagger &&
     npm install &&
     export PATH=$(npm bin):$PATH &&
     python3 setup.py install &&
     cd ../coala &&
     coala --ci"
